### ISSUE TITLE
[Custom] Consider alternatives to images for modules

### ISSUE THREAD

**Issue by androidacy-user** [tiann/KernelSU#1403]
### Describe your problem.

Hello!

We understand that images probably are convenient for kernelsu purposes; however, this becomes extremely difficult when an app needs to manage and update its own module.

Our use case does not fit well with running the relevant cli command to install the module, as we need to populate and update files on the fly at runtime, and using a prepared module would be complex and highly impractical.

And with 0.8.0+, the ksu daemon appears to disregard our created sparse images, treating them as invalid and reverting to no modules installed.

We're open to discussion, but we feel that the current image situation does not fit well with advanced use cases.

**Comment by tiann** [comment]
What's your "advanced use cases"?  If you need to install module, use manager or cli, We have never supported manually installing modules yourself.

**Comment by tiann** [comment]
KernelSU's image has been a spare image since the day it was born. The new version increases the file size, removes e2fsck and expansion operations, but is otherwise the same.

**Comment by tiann** [comment]
> It is Incredibly difficult on Android to create and manage sparse files if you don't happen to be running at the kernel level

You don't have to run it at kernel level. just replace `cp` with `ksud debug xcp` is enough.

**Comment by tiann** [comment]
> We were able to manage on kernelsu versions that didn't use sparse images relatively okay, albeit with a lot of hacks.

If you choose to use non-standard methods to hack, you will one day face the problem of being unable to hack.

We plan to use ksufs to replace overlayfs in the future. Will you ask us to be compatible with older versions at that time?

**Comment by tiann** [comment]
> It's not so much "installing" as "using". There's just no clean way to make an installable zip, and our app(s) become quite pointless if we force users to manually install through kernelsu manager themselves, I think

You can generate the module zip and then manually call `ksud module install <ZIP>.

As far as I know, there are many apps that do this.

**Comment by tiann** [comment]
You used a non-public interface to install the module, which just happened to work on Magisk.

Many modules use cli to install modules, in Magisk they use `magisk --install-modules`, in KernelSU they use `ksud module install`, they work fine. You can use the `su` command to call it without user intervention, and there is no behavior that forces users to install the manager.

During the evolution of the framework, only the compatibility of the public interfaces is guaranteed, and you rely on the internal behavior of the framework. This cannot be guaranteed in any software development process, and we will not provide this guarantee.

**Comment by tiann** [comment]
> Which requires more work from everyone else purely because you don't follow an established system, choosing to instead break it.

You're relying on framework internal behavior, and it's you who are not adhering to the standard, not us.

**Comment by tiann** [comment]
> Also magisk BusyBox that you so happily use? That's technically internal API. Bet you wouldn't be happy if they made that work in unexpected ways.

Magisk's busybox is clearly a public API, as stated in [its documentation](https://topjohnwu.github.io/Magisk/guides.html#busybox).

> So essentially your approach is extremely hostile to any use cases you don't consider standard

We will not stop you from hacking, but since you have to rely on our internal implementation, why not just look at the source code directly? If you look at the code, you will find that all you need to do is change "cp" to "xcp" and its behavior will be exactly the same as before.

You used a strange method to hack and now our internal code changes have rendered this hack ineffective. Yet you blame us? If you want to hack, please make sure you understand the internal implementation of our program and continuously update your hacking skills. Otherwise, isn't it just working randomly?

For example, we have created a toaster that can toast bread with just one button press; if you find that this method doesn't produce tasty toast, and you decide to take it apart and add other components to it, and later on we update the toaster's circuit and your method no longer works, you should reconnect the circuit instead of blaming the toaster manufacturer, because the button for toasting bread has never changed.
