### ISSUE TITLE
porting KernelSU to android kernel3.18 failed

### ISSUE THREAD

**Issue by dabao1955** [tiann/KernelSU#539]
**Describe the bug**
porting KernelSU to android kernel3.18 failed
**To Reproduce**
Steps to reproduce the behavior:make ARCH=arm64 \
                                  O=../out \
                                  CLANG_TRIPLE=aarch64-linux-gnu- \
                                  CROSS_COMPILE=$HOME/aarch64-linux-android-4.9>
                                  CROSS_COMPILE_ARM32=$HOME/arm-linux-androidea>

**Expected behavior**
build complete
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OPPO R9S
 - OS: lineageos
 - Version 14
 - kernel version:3.18

**Additional context**

 CC      drivers/input/touchscreen/of_touchscreen.o
/home/synaptic/linux-3.18/drivers/kernelsu/ksu.c: In function 'kernelsu_init':
/home/synaptic/linux-3.18/drivers/kernelsu/ksu.c:60:2: warning: #warning ("KPROBES is disabled, KernelSU may not work, please check https://kernelsu.org/guide/how-to-integrate-for-non-gki.html") [-Wcpp]
error, forbidden warning: ksu.c:60
make[3]: *** [/home/synaptic/linux-3.18/scripts/Makefile.build:257: drivers/kernelsu/ksu.o] エラー 1
make[2]: *** [/home/synaptic/linux-3.18/scripts/Makefile.build:402: drivers/kernelsu] エラー 2
make[2]: *** 未完了のジョブを待っています....

CC      drivers/irqchip/irq-gic-common.o
/home/synaptic/linux-3.18/drivers/kernelsu/allowlist.c: In function 'do_load_allow_list':
/home/synaptic/linux-3.18/drivers/kernelsu/allowlist.c:175:3: warning: format '%d' expects argument of type 'int', but argument 2 has type 'long int' [-Wformat=]
error, forbidden warning: allowlist.c:175
make[3]: *** [/home/synaptic/linux-3.18/scripts/Makefile.build:257: drivers/kernelsu/allowlist.o] エラー 1
make[2]: *** [/home/synaptic/linux-3.18/scripts/Makefile.build:402: drivers/kernelsu] エラー 2
make[2]: *** 未完了のジョブを待っています....
  CC      drivers/iommu/iommu-sysfs.o

**Comment by tiann** [comment]
KernelSU does not support kernels below version 4.4. If you are interested, you can try it on your own, but this requires some kernel-related knowledge, as some features may not be available on lower versions of the kernel. It is not as simple as compiling the source code.

**Comment by ananjaser1211** [comment]
If anyone in the future is searching for 3.18, i have managed to get it working on my samsung galaxy S7 with 3.18.140

Notes : This only compiles with Werror disabled, there are few casting errors in ksu_handle_prctl , apk_sign check_block and few others i did not have the urge to fix, but i assume they will cause errors later on. Also it works while having Selinux enforcing so thats nice.

I also tested some modules like Zygisk on kernelSU and youtube-revanced-magisk

Thanks @tiann for kernelSU, it is amazing and i have been using it on pretty much all my phones.

You mainly need : 
[kernel: groups: expose groups_sort](https://github.com/ananjaser1211/Cronos_8890/commit/cd5ac4d7ad2eed13f6b5575d1df8c71bc347dee5)
[configs: exynos8890: Enable overlayfs](https://github.com/ananjaser1211/Cronos_8890/commit/9cf393028e1d0f859c41405b57589295b0c40138)
[syscalls: implement execveat() system call](https://github.com/ananjaser1211/Cronos_8890/commit/cc4dee0fabff1e3a6a6a0af23f97b769563aab59)
[VFS: Split DCACHE_FILE_TYPE into regular and special types](https://github.com/ananjaser1211/Cronos_8890/commit/403e0b452f96160c50b1c6d4e0bdc8e68a423692)

VFS and friends :

[VFS: (Scripted) Convert S_ISLNK/DIR/REG(dentry->d_inode) to d_is_*(de…](https://github.com/ananjaser1211/Cronos_8890/commit/98791cf02e06a110c91fb42e386040578be0fde3)
[VFS: Fix up debugfs to use d_is_dir() in place of S_ISDIR()](https://github.com/ananjaser1211/Cronos_8890/commit/b83468f2223c6c26af475bf4340944c02a5c5814)

The most difficult however is you need LSM_HOOKS which was not in my 3.18 kernel, i was able to pick it from 4.4 kernel source, but it needed some work
You can start at [LSM: Split security.h] (https://github.com/ananjaser1211/Cronos_8890/commit/af0db6c0b540216f182c0aa9f3cc5bac48c86d29) and go up

From how to implement on non GKI
[fs: Add KernelSU calls manually](https://github.com/ananjaser1211/Cronos_8890/commit/e6405293114ec6813e5f84059671beecd50b8aa8)
[selinux: Allow init exec ksud under nosuid](https://github.com/ananjaser1211/Cronos_8890/commit/f9704487afdad8fc4295a492d054eada39a0eb0b)

FInally i need to edit the fetcher because 3.18 has different headers for input (we dont split input codes) we also needed uaccess header and AIO header for kiocb


```
# 3.18 Kernel Patches

# Fix pointer error
sed -i 's/PTR_ERR(fp));/ (int)PTR_ERR(fp));/' uid_observer.c

# Add uaccess Header
sed -i '/#if LINUX_VERSION_CODE < KERNEL_VERSION(4, 10, 0)/i #include "linux/uaccess.h"' kernel_compat.c

# Add AIO Header To address kiocb on 3.18
sed -i '/#include "allowlist.h"/i #include "linux/aio.h"' ksud.c

# Use input.h Header instead of input-event-codes.h
sed -i 's/#include "linux\/input-event-codes.h"/#include "linux\/input.h"/' ksud.c

# Remove unsupported cflags
sed -i 's/ccflags-y += -Wno-implicit-function-declaration -Wno-strict-prototypes -Wno-int-conversion -Wno-gcc-compat/ccflags-y += -Wno-implicit-function-declaration -Wno-strict-prototypes/' Makefile
```

# ROOT test

![photo_2023-10-15_17-52-56](https://github.com/tiann/KernelSU/assets/25624482/568687ac-034d-4dfa-ad71-a04385db359b)
![photo_2023-10-15_17-53-02](https://github.com/tiann/KernelSU/assets/25624482/48a69d89-a1d9-4e83-a40e-62890158d5e9)
![Screenshot_2](https://github.com/tiann/KernelSU/assets/25624482/3a075eaa-98b9-460c-b033-e0765f5ad574)

# Module
![photo_2023-10-15_17-59-05](https://github.com/tiann/KernelSU/assets/25624482/6f4ac12a-129f-416e-99a3-3fe41a87f416)
![photo_2023-10-15_17-59-00](https://github.com/tiann/KernelSU/assets/25624482/57998c40-a182-48f7-8348-43a4339af7f9)
 Test

**Comment by ananjaser1211** [comment]
Update, For module support to work on 3.18 (Zygisk for example) it wont initialize properly and would not mount, the solution in my case was upstreaming ovl (overlayfs) and whatever dependencies it needed in FS, i found it easy to cherry-pick directly from 4.4 kernel source. 

Range i picked : https://github.com/ananjaser1211/Cronos_8890//compare/3b260b125e3eb9508e9110043d795554215ec8cf...cab7f2b816073fcfe64543b21a44253a1697b7c6

This made zygisk work and made modules like LSposed work, i do notice in log when using Zygisk there is a CMD 12/13 error

```
<3>[  261.868202]  [3:      zygiskd64:21510] KernelSU: prctl reply error, cmd: 12
<3>[  261.868229]  [3:      zygiskd64:21510] KernelSU: prctl reply error, cmd: 13
```

I think its something in the REGS but i dont know how to read them yet, works otherwise.

**Comment by UDPSendToFailed** [comment]
@ananjaser1211 just wanted to say thanks, I picked those commits and even though they needed _some_ modifications for my device's msm kernel, KernelSU Next seems to be working perfectly.

![Image](https://github.com/user-attachments/assets/ad415a64-1f01-48cb-be60-66b195e714bc)

**Comment by backslashxx** [comment]
### For people looking for 3.x integration guide, I streamlined it here

- https://github.com/backslashxx/KernelSU/issues/20

Looks like thread hijacking, but thats just how it is.

I also recommend everyone who picked the old guide to update theirs.

However old guide is still here
<details>
  <summary>show old guide</summary>

!! warning this is old and buggy!
!!! YOUVE BEEN WARNED !!!
## notes, kernelsu on 3.10
- most things are also applicable on 3.18

### the main issue really
+ missing lsm_hooks (LSM_HOOK_INIT, security_add_hooks)

## detailed list for someone who wants to try.

### lsm_hooks is way different/non-existent. 
- instead of backporting this, hook the functions itself on security.c.
- https://github.com/backslashxx/KernelSU/issues/7
- remove LSM_HOOK_INIT, security_add_hooks and its handlers on ksu code https://github.com/tiann/KernelSU/commit/eae4393
- make sure to build with CONFIG_KSU_LSM_SECURITY_HOOKS=n

### do_execve / do_execve_common 
- used to use char filename which wont work, so your choices are, backport do_execve that uses struct filename on first arg
- backport https://github.com/torvalds/linux/commit/c4ad8f98bef77c7356aa6a9ad9188a6acc6b849d
- then follow this hook guide https://github.com/backslashxx/KernelSU/issues/5

#### OR hook on sys_execve instead with a modified execveat hook
- first line creates the struct for us, `struct filename *path = getname(filename);` so it is ready.
- reference for struct filename, https://elixir.bootlin.com/linux/v3.10.108/source/include/linux/fs.h#L1983
- so instead of passing `&filename`, pass `&path` as shown here https://github.com/backslashxx/android_kernel_zte_msm8952/commit/297fab0
- compatibility is not assured, but it is likely fine. 

### CONFIG_UIDGID_STRICT_TYPE_CHECKS
- if this is disabled remove .val as uid_t/gid_t wont be struct member
- edit this ksu side
- https://github.com/backslashxx/android_kernel_zte_msm8952/commit/e13328c
- reference: https://elixir.bootlin.com/linux/v3.10.108/source/include/linux/uidgid.h#L20

### get_cred_rcu
- just grab this from upstream https://github.com/torvalds/linux/commit/97d0fb239c041f5f99655af74812c3ab75cc4346

### path_umount, no MNT_LOCKED
- [comment out that MNT_LOCKED](https://github.com/backslashxx/android_kernel_zte_msm8952/commit/b3f6750) or backport MNT_LOCKED (optionally)
- path_umount https://github.com/tiann/KernelSU/pull/1464
- MNT_LOCKED, optional https://github.com/torvalds/linux/commit/5ff9d8a65ce80efb509ce4e8051394e9ed2cd942

### bin2hex 
- missing, just backport this https://github.com/torvalds/linux/commit/53d91c5ce0cb8945b55e8bb54e551cabc51eb28d

### strscpy is missing
- throne_tracker needs this
- strncpy seems to fail? null termination issue? (throne tracker gets stuck)
- just use strcpy? (works but very risky)
- can be hardened with a memset to clear destination + strncat (is ok but too much)
- middle ground is strncpy + null terminate. https://github.com/backslashxx/android_kernel_zte_msm8952/commit/069beff

### read_iter on file_operations struct is missing
- just put it in. `ssize_t (*read_iter) (struct kiocb *, struct iov_iter *);` on include/linux/fs.h, struct file_operations
- cherry pick from https://github.com/torvalds/linux/commit/293bc9822fa9b3c9d4b7893bcb241e085580771a

### groups_sort is not exported
- backport or just cherry pick
- backport, https://github.com/torvalds/linux/commit/bdcf0a423ea1c40bbb40e7ee483b50fc8aa3d758
- cherry-pick, https://github.com/ananjaser1211/Cronos_8890/commit/cd5ac4d7ad2eed13f6b5575d1df8c71bc347dee5

### d_is_reg() is missing
- can be adapted using IS_REG, git blame the kernel
- https://github.com/backslashxx/android_kernel_zte_msm8952/commit/a208ce6
- reference: https://github.com/torvalds/linux/commit/e36cb0b89ce20b4f8786a57e8a6bc8476f577650

### NNP / nosuid exec support 
- `selinux: reject setexeccon() on MNT_NOSUID applications with -EACCES
` https://github.com/torvalds/linux/commit/4f189988a0a5890db597ec48fc0e8b09922f290a
- `selinux: Permit bounded transitions under NO_NEW_PRIVS or NOSUID.
` https://github.com/torvalds/linux/commit/7b0d0b40cd78cadb525df760ee4cac151533c2b5
- then apply `allow init exec ksud under nosuid` https://github.com/LineageOS/android_kernel_oneplus_msm8998/commit/3df9df42a659f489091445d813b8c0477215ae3a



### others
#### then mostly just compiler issues, will likely just be warnings, depending on your compiler setup
- cast all PTR_ERR to int, so (int)PTR_ERR, %ld to %d on pr_err after that
- copy_to_user, cast all arg to void *, eg, copy_to_user((void __user *)arg3
- https://github.com/backslashxx/android_kernel_zte_msm8952/commit/cda84c2

#### overlayfs, this is kinda too much to upstream for 3.10
- you have to upstream this to atleast 4.0-rc1
- for official ksu, you need to be atleast on par to this https://github.com/torvalds/linux/commit/a78d9f0d5d5ca9054703376c7c23c901807ddd87
- just adapt MKSU and use magic mount.
- merged in support for legacy android too https://github.com/5ec1cff/KernelSU/commit/b28789ac7a39e36e90103dbfe48786e170d2b098 

#### ext4_unregister_sysfs() is missing on old ext4
- just revert https://github.com/tiann/KernelSU/commit/de29115
- create dummy look-alike function? https://github.com/backslashxx/android_kernel_zte_msm8952/commit/e60f7f0
- not really needed if using magic mount variant, just revert

backporting full do_execveat_common and lsm_hooks split-up from security.h is NOT needed.
while those are GOOD, those are HARDER.

here is a full demo of kernelsu for 3.10 
https://github.com/backslashxx/android_kernel_zte_msm8952/commits/ksu-3.10

same one but with heavier emphasis on backports
https://github.com/backslashxx/android_kernel_zte_msm8952/commits/ksu-3.10-backport-heavy

</details>

**Comment by ananjaser1211** [comment]
@backslashxx KernelSU on 3.10! this is incredible, makes me want to pull out my good ol note 4 to try it out, well done!

**Comment by backslashxx** [comment]
@Meghthedev finally someone that isnt me running KSU on 3.10

**Comment by NCLnclNCL** [comment]
> [@Meghthedev](https://github.com/Meghthedev) finally someone that isnt me running KSU on 3.10
> 
> good job man!

Hello, i have redmi 5 plus with 3.18, can i build kernelsu with github action?, and can it integrate susfs?

**Comment by ZetLink** [comment]
@backslashxx Thank you for your work, I managed to make it work thanks to your commits. Here running on Google Nexus 5X.

![Image](https://github.com/user-attachments/assets/5708fb0d-c450-4ea8-acba-1532f4bceacb)

**Comment by backslashxx** [comment]
@ZetLink theres another optimization you can pick from @acroreiser, where it puts throne tracker to a kthread

heres the original for 3.4
https://github.com/acroreiser/android_kernel_lge_hammerhead/commits/lineage-22.2-kernelsu/

here it is rebased for 3.10
https://github.com/ximi-libra-test/android_kernel_xiaomi_libra/compare/1420b7e...71976c1

**Comment by rapeazabe888** [comment]
Duplicate of #2234

**Comment by backslashxx** [comment]
@ZetLink @Meghthedev @fakemanoan 
I recommend you guys update and sync with the new guide.
- https://github.com/backslashxx/KernelSU/issues/20

I did some things to support UL properly.

**Comment by zdrawko420** [comment]
Hello!
Which ToolChain clang should I use and what's the command to start compiling?
