### ISSUE TITLE
ANXCamera Magisk Module

### ISSUE THREAD

**Issue by Theo-user** [tiann/KernelSU#719]
**Describe the bug**
After installing the module without errors the ANX camera apk crashes when launching. Errors here:
https://paste.crdroid.net/jgWxeP

**To Reproduce**
Install module here: https://androidfilehost.com/?fid=14655340768118463076
Restart and run ANXCamera

**Expected behavior**
Load the camera like when using Magisk.

**Screenshots**

**Smartphone (please complete the following information):**
Poco F3
Crdroid 9.14
InfiniR_Alioth_v2.67 kernel

**Additional context**
I have an issue when using Magisk without Zygist and and with MagiskHide. I need to allow SU for the camera apk. Doing this with KernelSU doesn't resolve the issue like with Magisk. It's most likely permissions but I've not been able to pinpoint it.

**Comment by tiann** [comment]
Disable the "umount modules by default" in settings and try it again.

**Comment by Theo-user** [comment]
Same error https://paste.crdroid.net/ljOhZA

**Comment by Theo-user** [comment]
Still not working with 0.6.2

**Comment by tiann** [comment]
What if you give root permission to the camera?

**Comment by Theo-user** [comment]
I did both as you suggested but the error persists. Root permission is required for the camera with Magisk if I use Magisk hide and enforced root. No such luck with KernelSU.

**Comment by tiann** [comment]
Please upload the bugreport in KernelSU manager.

**Comment by Theo-user** [comment]
[KernelSU_bugreport_2023-07-11_16_23.tar.gz](https://github.com/tiann/KernelSU/files/12016357/KernelSU_bugreport_2023-07-11_16_23.tar.gz)

**Comment by tiann** [comment]
I think this is a module issue, the log show that:

> open libmialgoengine.so failed

But the module don't have any file named that.

**Comment by tiann** [comment]
Please exec ls -alZ /vendor

**Comment by Theo-user** [comment]
![Screenshot_20230711-173619_Termux](https://github.com/tiann/KernelSU/assets/75871295/b88766f3-e242-476c-9f76-ddb1ab618748)

**Comment by tiann** [comment]
Please use `adb shell` and `su` to list the files:

1. adb shell
2. su
3. ls -alZ /vendor/lib64

**Comment by Theo-user** [comment]
Will this suffice?

[output.txt](https://github.com/tiann/KernelSU/files/12022960/output.txt)

**Comment by tiann** [comment]
Did you use `su` to execute it?

**Comment by tiann** [comment]
Please use adb shell or other terminal emulator, the SELinux context is missing.

**Comment by Theo-user** [comment]
[output.txt](https://github.com/tiann/KernelSU/files/12023149/output.txt)

**Comment by tiann** [comment]
the logcat file of your bugreport is empty.

**Comment by Theo-user** [comment]
Please check this one

[KernelSU_bugreport_2023-07-12_04_21.tar.gz](https://github.com/tiann/KernelSU/files/12023426/KernelSU_bugreport_2023-07-12_04_21.tar.gz)

**Comment by tiann** [comment]
Please use adb shell execute `setprop debug.ld.all dlopen,dlerror` and reproduce the bug and then upload the bugreport.

**Comment by tiann** [comment]
I believe this is a module issue.

Your logcat shows that:

> 07-12 04:21:31.528  4031  4031 D MiCamAlgoInterfaceJNI: static initializer: loadLibrary camera_algoup_jni.xiaomi
07-12 04:21:31.529  4031  4031 E vndksupport: Could not load /vendor/lib64/libmialgoengine.so from sphal namespace: dlopen failed: library "/vendor/lib64/libmialgoengine.so" not found.
07-12 04:21:31.529  4031  4031 E MI_Algo_JNI: init: open /vendor/lib64/libmialgoengine.so error: (null)
07-12 04:21:31.529  4031  8350 D SharedPreferencesImpl: Time required to fsync /data/user/0/com.android.camera/shared_prefs/camera_settings_global.xml: [<1: 0, <2: 0, <4: 0, <8: 0, <16: 0, <32: 0, <64: 0, <128: 0, <256: 0, <512: 1, <1024: 0, <2048: 0, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
07-12 04:21:31.529  4031  4031 D AndroidRuntime: Shutting down VM
07-12 04:21:31.530  4031  4031 E AndroidRuntime: FATAL EXCEPTION: main
07-12 04:21:31.530  4031  4031 E AndroidRuntime: Process: com.android.camera, PID: 4031
07-12 04:21:31.530  4031  4031 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.android.camera.LocalParallelService: java.lang.RuntimeException: open libmialgoengine.so failed!
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4522)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:257)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2099)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7833)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: Caused by: java.lang.RuntimeException: open libmialgoengine.so failed!
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(Native Method)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at com.xiaomi.engine.MiCameraAlgo.init(Unknown Source:39)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at com.android.camera.LocalParallelService$LocalBinder.initMiviEngine(Unknown Source:24)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at com.android.camera.LocalParallelService$LocalBinder.<init>(Unknown Source:55)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at com.android.camera.LocalParallelService.onCreate(Unknown Source:31)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4509)
07-12 04:21:31.530  4031  4031 E AndroidRuntime: 	... 9 more

And i decompile your camera APK: 

```java
public class MiCamAlgoInterfaceJNI {
    public static final String LIB_NAME = "camera_algoup_jni.xiaomi";
    public static final String TAG = "MiCamAlgoInterfaceJNI";

    static {
        try {
            Log.e(MiCamAlgoInterfaceJNI.class.getSimpleName(), "start loading camera_algoup_jni.xiaomi");
            System.loadLibrary(LIB_NAME);
            Log.d(TAG, "static initializer: loadLibrary camera_algoup_jni.xiaomi");
        } catch (UnsatisfiedLinkError e) {
            String str = TAG;
            Log.e(str, "can not load library:camera_algoup_jni.xiaomi : " + Log.getStackTraceString(e));
        }
    }

    public static native long createSessionByOutputConfigurations(BufferFormat bufferFormat, List<OutputConfiguration> list, TaskSession.SessionStatusCallback sessionStatusCallback);

    public static native long createSessionWithSurfaces(BufferFormat bufferFormat, List<Surface> list, TaskSession.SessionStatusCallback sessionStatusCallback);

    public static native int deInit();

    public static native int destroySession(long j);

    public static native int flush(long j);

    public static native int getVersionCode();

    public static native int init(String str);

    public static native int processFrame(long j, FrameData frameData, TaskSession.FrameCallback frameCallback);

    public static native int processFrameWithSync(long j, List<FrameData> list, Image image, int i);

    public static native int setMiViInfo(String str);
}
```

And in `libcamera_algoup_jni.xiaomi.so`, it shows:

```cpp
  else
  {
    v26 = dlerror();
    __android_log_print(6LL, "MI_Algo_JNI", "init: open %s error: %s", "/vendor/lib64/libmialgoengine.so", v26);
    v27 = (*(__int64 (__fastcall **)(__int64 *, const char *))(*v8 + 48))(v8, "java/lang/RuntimeException");
    if ( v27 )
      (*(void (__fastcall **)(__int64 *, __int64, const char *))(*v8 + 112))(v8, v27, "open libmialgoengine.so failed!");
    (*(void (__fastcall **)(__int64 *, __int64))(*v8 + 184))(v8, v27);
    result = 0xFFFFFFFFLL;
  }
```

This is the error cause. But in my MIUI devices, it cannot open `/vendor/lib64/libmialgoengine.so` too, but it don't throw the error:

```cpp
  {
    v25 = sub_E978();
    sub_E750(6LL, "MI_Algo_JNI", "init: open %s error: %s", "/vendor/lib64/libmialgoengine.so", v25);
    result = 0xFFFFFFFFLL;
  }
```
