### ISSUE TITLE
Additional instruction when using kprobes

### ISSUE THREAD

**Issue by pascua28** [tiann/KernelSU#765]
Hi! I noticed that on the instructions page, you mentioned something about kprobes not properly working on some kernels. However, the issue might not be the kprobes implementation itself as most OEMs do not even touch that code. Most of the kernels I inspected do not have some of the functions probed by kernelsu.

These functions include:
`__do_execve_file()`, `do_execveat_common()` and `input_handle_event()`.

While kallsyms can be used for this, it might complicate the code a bit.
Exporting them via `EXPORT_SYMBOL_GPL()` instead makes them visible to `kprobes_register()`.

This can be confirmed by running this command:
`cat /sys/kernel/debug/kprobes/list`

**Comment by tiann** [comment]
Just because the vendor didn't use this part of the code, it might not work at all; because Linux upstream often has breaking changes. On GKI kernels, vendors must use kprobe, so it must work well.

In addition, registering kprobe on an illegal symbol will not cause a bootloop. If you don’t believe it, you can just kprobe an existing symbol to see if the problematic device will bootloop.

**Comment by pascua28** [comment]
My concern is not about the kprobes itself or a need to fix it. It is about the visibility of some of the functions I mentioned above making kprobes registration fail on those functions.
