### ISSUE TITLE
How to uninstall the kernel su?

### ISSUE THREAD

**Issue by lixiao189** [tiann/KernelSU#780]
Now I don't need to use kernel su any more? How can I uninstall it?

**Comment by lixiao189** [comment]
I install it with custom Recovery with a modified kernel which is downloaded from github release page.

**Comment by tiann** [comment]
1. `rm -rf /data/adb/ksu*`
2. Flash stock boot.img

**Comment by git-Hmmm** [comment]
@tiann I've a file named
"ksud" in /data/adb
is it also ksu related file?

**Comment by tiann** [comment]
> @tiann I've a file named "ksud" in /data/adb is it also ksu related file?

Yes, it is.

**Comment by LeeBinder** [comment]
KernelSU Manager supposedly since v0.9.3:

> Support uninstall permanently and restore stock boot in Settings. You can restore stock boot before OTA to avoid download the full firmware.

Source: https://github.com/tiann/KernelSU/releases/tag/v0.9.3

.. but I don't see any such option in Settings, not even in the latest [KernelSU_v0.9.3-15-g646b6f7_11819-release.apk](https://github.com/tiann/KernelSU/actions/runs/8875136829/artifacts/1455993873) [via Actions](https://github.com/tiann/KernelSU/actions/workflows/build-manager.yml?query=is%3Asuccess)..

**Comment by eitan-pmw** [comment]
I want to move over to Magisk because of device integrity checks. I already installed it, and now I have file `/data/adb/ksu/bin/magiskboot`. Is it safe to delete?

**Comment by ZeizerS** [comment]
Does anyone here know how to move RootKSU to magisk?
