### ISSUE TITLE
The ./ksud module list command cannot list modules under TWRP

### ISSUE THREAD

**Issue by huangsijun17** [tiann/KernelSU#867]
>               No, there isn't. You can adb push `ksud` to TWRP and use the cli to manage module, or just delte `/data/adb/ksu/`.
> KernelSU have no plan to support recovery mode now.
> 
> _Originally posted by @tiann in https://github.com/tiann/KernelSU/issues/34#issuecomment-1374974165_
            
```
/data/adb/ksu/bin # ./ksud module
Manage KernelSU modules

Usage: ksud module <COMMAND>

Commands:
  install    Install module <ZIP>
  uninstall  Uninstall module <id>
  enable     enable module <id>
  disable    disable module <id>
  list       list all modules
  help       Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
2|OP591BL1:/data/adb/ksu/bin # ./ksud module list
[]
```

**Comment by tiann** [comment]
This is expected behavior, we have no plan to make it run in Recovery mode.

If you insist, you can look through the ksud source code and you'll find the answer. I won't tell you directly because I don't think it's a recommended operation.

**Comment by devnoname120** [comment]
@huangsijun17

You need to execute this command before:
```
mount -t ext4 -o rw /data/adb/ksu/modules.img /data/adb/modules
```

---------------

The reason is that for all the commands `ksud` assumes that `/data/adb/ksu/modules.img` was [already mounted](https://github.com/tiann/KernelSU/blob/f52beb9f75a44f4753d839980b92864eef6735e4/userspace/ksud/src/module.rs#L615-L616) to `/data/adb/modules` by KSU during boot.

The annoying thing is that `ksud` doesn't show any error or warning if `/data/adb/modules` is not mounted.

This makes it really hard to figure out what's wrong and fix a bootloop when you are not able to boot into safemode to disable your modules:
- If you flash the stock `boot.img` then you can boot normally but the KSU manager can't access its configuration so you can't disable modules.
- If you don't flash the stock `boot.img` then it doesn't boot and you can't change KSU's configuration either. So you're stuck and the trick above is the only clean way to be able to fix things.
