### ISSUE TITLE
Device Hangs and Reboots After Installing Module on Xiaomi Redmi Note 4 (mido)

### ISSUE THREAD

**Issue by ramhaidar** [tiann/KernelSU#910]
**Describe the bug**
Kernel: lineage-20.0 v4.9.337 — Xiaomi Redmi Note 4 (mido)
Succesfully build the kernel with KernelSU integrated into it and succesfully flashed it into my device. Superuser work normal but when i tried to install any module it show succes on the Module tab log but after that the device hang and can't be interacted with then around 3 second it reboot itself.
After reboot the module installed gone from Module Tab.

**To Reproduce**
Steps to reproduce the behaviour:
1. Kernel Source: [Link](https://www.mediafire.com/file/h5d5gkumnx3exhr/Mido_Kernel_4.9.tar.xz/file) | Kernel Build (AnyKernel3): [Link](https://www.mediafire.com/file/ek4vwob3bllcajw/KernelSU_AnyKernel3.zip/file).
2. Build the kernel from source or use the build from above.
3. Flash it using recovery.
4. Boot into system and open KernelSU Manager app.
5. Superuser work normally.
6. Install the module.

**Expected behaviour**
Module tab log show module succesfully installed but the device hang and rebooted itself.

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~
Device hangs and reboots itself unable to take screenshots from it.

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Redmi Note 4]
 - OS: [Android]
 - Version [11]

**Additional context**
Superuser working and apps can get root acces.
Tried using and not using [4.9 kernel version patch](https://github.com/tiann/KernelSU/issues/419#issuecomment-1518923973) still the same result.
Integrated using the [manual method](https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#manually-modify-the-kernel-source) from KernelSU.org (Kernel is not GKI and KProbe broken).
Did not enabled KernelSU's builtin SafeMode.
After reboot the module installed gone from Module Tab.

[KernelSU Logs Before Installing Module](https://www.mediafire.com/file/bnl874cdeh3zf04/KernelSU_bugreport_2023-08-29_04_25_before.tar.gz/file)
[KernelSU Logs After Installing Module](https://www.mediafire.com/file/4nkmlka0bta1yob/KernelSU_bugreport_2023-08-29_04_27_after.tar.gz/file)

**Comment by tiann** [comment]
Please check the tutorial in official website, if kprobe is not working, try integrate it manually

**Comment by ramhaidar** [comment]
Ah, sorry I didn't include that information earlier. Right, I built the kernel above using the manual integrate method and not the kprobe one (tried using kprobe but the device is going bootloop and won't boot).

**Comment by kamikaonashi** [comment]
the issue lies within zeelogs kernel itself, on /fs/ext4/page-io.c to be exact.
i just made a kernel with working modules for mido

**Comment by ramhaidar** [comment]
> the issue lies within zeelogs kernel itself, on /fs/ext4/page-io.c to be exact. i just made a kernel with working modules for mido

glad if it can be fixed, do you mind to share the commit diff for the page-io.c?

**Comment by kodhh** [comment]
i use the ext4 driver from oneplus_sdm845, that was fixed.

**Comment by ramhaidar** [comment]
> i use the ext4 driver from oneplus_sdm845, that was fixed.

Should i use the whole folder of ext4 or just the ext4/page-io.c ?

**Comment by TogoFire** [comment]
The useless ext4 commits that can break modules are:
"EXT4 optimizations"
"ext4: shrink directories on dentry delete"
"ext4: return lblk from ext4_find_entry"
"ext4: make dioread_nolock the default"
"ext4: improve smp scalability for inode generation [1/2]"
"ext4: improve smp scalability for inode generation [2/2]"
"ext4: Add no_sehash_xattr mount option"
"BACKPORT: ext4: add handling for extended mount options"

And remove the vmalloc backports commits, as it breaks the installation of the modules:
"mm: make vm_committed_as_batch aware of vm overcommit policy"
"Backport new vmalloc for "large performance benefits""

Decent updated and stable base for kernel 4.9:
https://github.com/TogoFire/msm-4.9

**Comment by ramhaidar** [comment]
Thank you @TogoFire for the response 🔥💖

**Comment by zeta96** [comment]
I have the same problem, for me, i just updated overlayfs if your kernel based codelinaro of caf, and then pick commit nosuid for old kernel, also only revert "ext4: make dioread_nolock the default" if you have it because this commit make module cant installed or hang  reboot when you installing module in kernelsu manager, dont enable kprobes because broken, btw i just picked some from togofire source without revert "ext4 optimization" or "ext4: shrink directories on dentry delete"

i dont have this commit "ext4: make dioread_nolock the default" in my another kernel source, but with all of  this commit kernelsu works fine, maybe for now is ok
"EXT4 optimizations"
"ext4: shrink directories on dentry delete"
"ext4: return lblk from ext4_find_entry"
"ext4: improve smp scalability for inode generation [1/2]"
"ext4: improve smp scalability for inode generation [2/2]"
"ext4: Add no_sehash_xattr mount option"
"BACKPORT: ext4: add handling for extended mount options"

i have vmalloc backport, but kernelsu is fine

**Comment by zeta96** [comment]
I have the same problem, for me, i just updated overlayfs if your kernel based codelinaro of caf, and then pick commit nosuid for old kernel, also only revert "ext4: make dioread_nolock the default" if you have it because this commit make module cant installed or hang  reboot when you installing module in kernelsu manager, dont enable kprobes because broken

i dont have this commit "ext4: make dioread_nolock the default" in my another kernel source, but with all of  this commit kernelsu works fine, maybe for now is ok
"EXT4 optimizations"
"ext4: shrink directories on dentry delete"
"ext4: return lblk from ext4_find_entry"
"ext4: improve smp scalability for inode generation [1/2]"
"ext4: improve smp scalability for inode generation [2/2]"
"ext4: Add no_sehash_xattr mount option"
"BACKPORT: ext4: add handling for extended mount options"

i have vmalloc backport for large performance, but kernelsu is fine

again, mostly msms8953 have this commit "ext4: make dioread_nolock the default"

**Comment by zeta96** [comment]
> Thank you @TogoFire for the response 🔥💖

I have the same problem, for me, i just updated overlayfs if your kernel based codelinaro of caf, and then pick commit nosuid for old kernel, also only revert "ext4: make dioread_nolock the default" if you have it because this commit make module cant installed or hang  reboot when you installing module in kernelsu manager, dont enable kprobes because broken

i dont have this commit "ext4: make dioread_nolock the default" in my another kernel source, but with all of  this commit kernelsu works fine, maybe for now is ok
"EXT4 optimizations"
"ext4: shrink directories on dentry delete"
"ext4: return lblk from ext4_find_entry"
"ext4: improve smp scalability for inode generation [1/2]"
"ext4: improve smp scalability for inode generation [2/2]"
"ext4: Add no_sehash_xattr mount option"
"BACKPORT: ext4: add handling for extended mount options"

i have vmalloc backport for large performance, but kernelsu is fine

again, mostly msms8953 have this commit "ext4: make dioread_nolock the default" also this bad

**Comment by zeta96** [comment]
> Thank you @TogoFire for the response 🔥💖

I have the same problem, for me, i just updated overlayfs if your kernel based codelinaro of caf, and then pick commit nosuid for old kernel, also only revert "ext4: make dioread_nolock the default" if you have it cause this makes module cant installed or hang  reboot when you installing module in kernelsu manager, dont enable kprobes because broken, 

i just picked some from TogoFire source without revert  "ext4: optimization" because with or without by default the os i use usually use nobarrier, 
also without revert  "ext4: shrink directories on dentry delete" and others

i dont have this commit "ext4: make dioread_nolock the default" in my another kernel source, but with all of  this commit kernelsu works fine, maybe for now is ok
"EXT4 optimizations"
"ext4: shrink directories on dentry delete"
"ext4: return lblk from ext4_find_entry"
"ext4: improve smp scalability for inode generation [1/2]"
"ext4: improve smp scalability for inode generation [2/2]"
"ext4: Add no_sehash_xattr mount option"
"BACKPORT: ext4: add handling for extended mount options"

i have vmalloc backport for large performance, but kernelsu is fine

again, mostly msms8953 have this commit "ext4: make dioread_nolock the default", just dont pick this commit or revert if you have it
